---
- hosts: all
  
  become: yes
  
  tasks:
  
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
  
  - name: reboot hosts
    reboot:
         msg: "Reboot initiated by Ansible"
         connect_timeout: 5
         reboot_timeout: 600
         pre_reboot_delay: 0
         post_reboot_delay: 30
         
  - name: ckeck uptime
    shell: uptime
