- hosts: all
  become: yes
  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: Reboot hosts and wait for it to restart
    reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
